name: Test & Deploy CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
    - name: Setup gcloud environment
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - run: yarn install
    - run: yarn build
    #- run: yarn test
    - run: gcloud app deploy -q
